package mirror

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type Mirror struct {
	outputDir    string
	destSkipTLS  bool
	configFile   string
	workspaceDir string
}

func New(outputDir string, destSkipTLS bool) (*Mirror, error) {
	configFile := filepath.Join(outputDir, "imageset-config.yaml")
	if _, err := os.Stat(configFile); err != nil {
		return nil, fmt.Errorf("imageset-config.yaml が見つかりません (先に generate を実行してください): %w", err)
	}

	absConfig, _ := filepath.Abs(configFile)
	absOutput, _ := filepath.Abs(outputDir)
	workspaceDir := filepath.Join(absOutput, "oc-mirror-workspace")

	return &Mirror{
		outputDir:    absOutput,
		destSkipTLS:  destSkipTLS,
		configFile:   absConfig,
		workspaceDir: workspaceDir,
	}, nil
}

// Execute は Mirror VM 上で oc-mirror を直接実行する
// destination は $(hostname -f):8443 を自動使用
func (m *Mirror) Execute() error {
	if _, err := exec.LookPath("oc-mirror"); err != nil {
		return fmt.Errorf("oc-mirror が PATH に見つかりません")
	}

	// Mirror VM 上で実行する前提: ホスト名を自動取得
	hostname, err := os.Hostname()
	if err != nil {
		return fmt.Errorf("ホスト名の取得に失敗: %w", err)
	}
	dest := fmt.Sprintf("docker://%s:8443", hostname)

	args := []string{
		"--v2",
		"-c", m.configFile,
		"--workspace", fmt.Sprintf("file://%s", m.workspaceDir),
		dest,
	}
	if m.destSkipTLS {
		args = append(args, "--dest-tls-verify=false")
	}
	args = append(args, "--log-level", "info")

	fmt.Fprintf(os.Stderr, "==> oc-mirror %s\n", strings.Join(args, " "))

	cmd := exec.Command("oc-mirror", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// DumpScript は Mirror VM で実行するシェルスクリプトを stdout に出力する
func (m *Mirror) DumpScript() error {
	tlsFlag := ""
	if m.destSkipTLS {
		tlsFlag = "\n  --dest-tls-verify=false \\"
	}

	script := fmt.Sprintf(`#!/usr/bin/env bash
# Generated by: oc-mirctl mirror --dump-script
# oc-mirror v2 (mirrorToMirror) 用スクリプト
#
# このスクリプトは Mirror VM 上で実行すること。
# destination は自動的に $(hostname -f):8443 に解決される。
#
# 使い方:
#   scp run-mirror.sh imageset-config.yaml pull-secret.json mirror-ca.pem ec2-user@<mirror-vm>:/tmp/mirror-work/
#   ssh ec2-user@<mirror-vm> 'bash /tmp/mirror-work/run-mirror.sh'

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIRROR_DEST="$(hostname -f):8443"
CONFIG="${SCRIPT_DIR}/imageset-config.yaml"
WORKSPACE="${SCRIPT_DIR}/oc-mirror-workspace"
LOG="${SCRIPT_DIR}/oc-mirror.log"

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

# ---- 前提チェック ----
command -v oc-mirror &>/dev/null || die "oc-mirror が PATH に見つかりません"
[ -f "$CONFIG" ] || die "imageset-config.yaml が見つかりません: $CONFIG"

# ---- CA 証明書の登録 ----
MIRROR_CA="${SCRIPT_DIR}/mirror-ca.pem"
if [ -f "$MIRROR_CA" ]; then
  info "Mirror Registry の CA 証明書をシステムに登録..."
  if [ -d /etc/pki/ca-trust/source/anchors ]; then
    sudo cp "$MIRROR_CA" /etc/pki/ca-trust/source/anchors/mirror-registry-ca.pem
    sudo update-ca-trust
  elif [ -d /usr/local/share/ca-certificates ]; then
    sudo cp "$MIRROR_CA" /usr/local/share/ca-certificates/mirror-registry-ca.crt
    sudo update-ca-certificates
  fi
fi

# ---- pull-secret に mirror registry の認証を追加 ----
# mirror registry のユーザー名/パスワードを環境変数で指定可能:
#   MIRROR_USER (default: init), MIRROR_PASSWORD (default: mirror-admin-password)
PULL_SECRET="${SCRIPT_DIR}/pull-secret.json"
if [ -f "$PULL_SECRET" ] && command -v jq &>/dev/null; then
  MIRROR_USER="${MIRROR_USER:-init}"
  MIRROR_PASSWORD="${MIRROR_PASSWORD:-mirror-admin-password}"
  MIRROR_AUTH=$(echo -n "${MIRROR_USER}:${MIRROR_PASSWORD}" | base64 -w0)

  MERGED=$(jq --arg host "$MIRROR_DEST" --arg auth "$MIRROR_AUTH" \
    '.auths[$host] = {"auth": $auth}' "$PULL_SECRET")

  # 認証ファイルを配置
  XDG="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
  mkdir -p "$XDG/containers" 2>/dev/null || true
  echo "$MERGED" > "$XDG/containers/auth.json" 2>/dev/null || true

  mkdir -p "$HOME/.docker"
  echo "$MERGED" > "$HOME/.docker/config.json"

  info "pull-secret をマージしました ($(echo "$MERGED" | jq -r '.auths | keys | length') registries)"
fi

# ---- oc-mirror v2 実行 ----
info "oc-mirror --v2 を実行 (mirrorToMirror)..."
info "  Config:    $CONFIG"
info "  Workspace: $WORKSPACE"
info "  Dest:      docker://${MIRROR_DEST}"
info "  Log:       $LOG"
info ""

mkdir -p "$WORKSPACE"

oc-mirror --v2 \
  -c "$CONFIG" \
  --workspace "file://$WORKSPACE" \
  "docker://${MIRROR_DEST}" \%s
  --log-level info 2>&1 | tee "$LOG"

# ---- 失敗イメージの skopeo フォールバック ----
# oc-mirror が manifest 互換性等で push に失敗したイメージを
# skopeo で amd64 single-arch として再 push する。
if grep -q "Failed to copy" "$LOG" 2>/dev/null; then
  info ""
  info "==> 失敗イメージの skopeo フォールバック..."

  if ! command -v skopeo &>/dev/null; then
    info "WARN: skopeo が見つかりません。フォールバックをスキップ"
  else
    FAILED_IMAGES=$(grep "Failed to copy" "$LOG" | grep -oP 'docker://\K[^ ]+' | sort -u)
    FB_OK=0
    FB_FAIL=0
    FB_SKIP=0

    for IMG in $FAILED_IMAGES; do
      REPO=$(echo "$IMG" | sed 's/@sha256:.*//')
      DIGEST=$(echo "$IMG" | grep -oP '@sha256:.*')
      TAG=$(echo "$REPO" | grep -oP ':[^/]+$' | sed 's/^://')
      REPO_CLEAN=$(echo "$REPO" | sed 's/:[^/]*$//')
      [ -z "$TAG" ] && TAG="latest"

      # まず manifest list かどうかを判定し、amd64 child digest を取得
      AMD64_DIGEST=$(skopeo inspect --raw "docker://${REPO_CLEAN}${DIGEST}" 2>/dev/null | \
        python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    manifests = data.get('manifests', [])
    if manifests:
        for m in manifests:
            if m.get('platform', {}).get('architecture') == 'amd64':
                print(m['digest']); break
    else:
        print('SINGLE')
except: pass
" 2>/dev/null)

      if [ -z "$AMD64_DIGEST" ]; then
        FB_SKIP=$((FB_SKIP + 1))
        continue
      fi

      # single manifest の場合は元の参照でそのままコピー
      if [ "$AMD64_DIGEST" = "SINGLE" ]; then
        SRC="docker://${REPO_CLEAN}${DIGEST}"
      else
        SRC="docker://${REPO_CLEAN}@${AMD64_DIGEST}"
      fi

      # destination: source の registry 部分を mirror に置き換え
      # nvcr.io/nvidia/foo → ${MIRROR_DEST}/nvidia/foo
      # registry.redhat.io/rhoai/bar → ${MIRROR_DEST}/rhoai/bar
      DEST_PATH=$(echo "$REPO_CLEAN" | sed 's|^[^/]*/||')
      DEST="docker://${MIRROR_DEST}/${DEST_PATH}:${TAG}"

      if skopeo copy "$SRC" "$DEST" --dest-tls-verify=false 2>/dev/null; then
        info "  OK:   ${REPO_CLEAN}:${TAG}"
        FB_OK=$((FB_OK + 1))
      else
        info "  FAIL: ${REPO_CLEAN}:${TAG}"
        FB_FAIL=$((FB_FAIL + 1))
      fi
    done

    info "  フォールバック結果: ${FB_OK} 成功, ${FB_FAIL} 失敗, ${FB_SKIP} スキップ"
  fi
fi

info ""
info "ミラーリング完了"
info "結果: $LOG"
info ""
info "次のステップ: クラスタに IDMS/CatalogSource を適用"
info "  oc-mirctl apply --results-dir ${WORKSPACE}/working-dir/cluster-resources/"
`, tlsFlag)

	fmt.Print(script)
	return nil
}
